### ISSUE TITLE
Time series Capacity Factor

### ISSUE THREAD

**Issue by obeles** [PyPSA/atlite#100]
I am currently trying to produce a hourly capacity factor time series but am running into some issues. It seems that the only way that atlite processes hourly time series is for energy generation, and that for capacity factors it only produces the average. Is there a specification in the parameters that could allow for an hourly capacity factor generation instead? This is the code Im working with: 

pv_CF = cutout.pv(pv_model,  capacity_factor=True , orientation={'slope': cutout_lat, 'azimuth': 0})

**Comment by fneum** [comment]
You can set `capacity_factor=False` and `per_unit=True` this should give you per-unit time series.

**Comment by obeles** [comment]
Im a bit confused over why setting `capacity_factor=False` and `per_unit=True` spits out the capacity factor time-series but it seems to be working. Thank you!
