### ISSUE TITLE
explicit mention of standard parallels for area calculation in runoff

### ISSUE THREAD

**Issue by martavp** [PyPSA/atlite#101]
I need to include the first and second standard parallels for the [Albers Equal Area projection](https://proj.org/operations/projections/aea.html) to work [when calculating runoff](https://github.com/PyPSA/atlite/blob/8534825a914ebc940d37dbdd611f77de3a4e83fc/atlite/convert.py#L551).

runoff *= (1000. / 24.) * xr.DataArray(basins.shapes.to_crs(dict(proj="aea")).area)

should be

runoff *= (1000. / 24.) * xr.DataArray(basins.shapes.to_crs(dict(proj="aea", lat_1=35, lat_2=60)).area)

I’m not sure if it is not an issue with the newer version, but I mentioned this here just in case.

**Comment by FabianHofmann** [comment]
fixed by #102
