### ISSUE TITLE
Add weather-dependent time-series for transmission line capacities

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/atlite#131]
## Detailed Description

Transmission capacities are influenced by the weather. We should add a conversion function for the cooling effect of transmission lines.  

## Possible Implementation

Goal: 
Add a conversion function `transmission`/`transmission_availability` (or different) in `atlite.convert`. 

Idea: Assume a set of transmission lines given as line shapes. 
1. For each line, calculate overlapping weather cells -> use `indicator_matrix` if it works between properly between line shapes and area shapes. Otherwise define a intersection matrix (booleans would probably be sufficient) .
2. @nworbmot suggested to take the maximum temperature along the line into account. This might be tricky and requires to define a new  aggregation function in `atlite.aggregate`. For a first shot, we could instead use the **mean** temperature over the whole line.
3. Enable wind angle data in cutouts. This variable is nowhere in the supported features. Probably it makes sense to enable a direct retrieving of specific ERA5 variables. 
4. Think about a clever implementation how to efficiently calculate the angle between wind direction and line direction. Probably it makes sense to calculate the to scale the (u, v) components (see table 2 in [ERA5 data doc](https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation#ERA5:datadocumentation-Dataformat)) to the components of a unit vector and do the same for the line direction. Then, calculate the dot product. if I'm not mistaken the current aggregation function would work for the average angle between wind and line.   
4. Do research and derive a formula for the combined cooling effect of temperature, wind speed + angle on the conduction capacity.

**Comment by fneum** [comment]
minimum wind speed
maximum temperature
