### ISSUE TITLE
Support horizontal tracking of pv panels 

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/atlite#140]
As suggested by @martavp, we should enable horizontal tracking of pv panels.

**Comment by Mastomaki** [comment]
I agree. But why only horizontal? Vertical too.

**Comment by euronion** [comment]
It was an effort efficiency considerations: Most tracking systems deployed today are horizontal tracking.

But I agree: single axis tracking and two axis tracking should both be implemented.

Would you consider an implementation of only vertical, single axis tracking also relevant?


Another consideration for tracking implementation:
Should tracking be implemented as follow-the-sun or optimised for efficiency? I vaguely remember that solar position tracking does not always provide optimal yield.

**Comment by Mastomaki** [comment]
At least there should be a possibility to add vertical single axis tracking because it is good in northern latitudes.

I suppose follow the sun is much simpler.
