### ISSUE TITLE
[JOSS] "community profile" checklist is incomplete

### ISSUE THREAD

**Issue by kanderso-nrel** [PyPSA/atlite#157]
GitHub has a checklist of repository-level community standards.  Here is the page for atlite: https://github.com/PyPSA/atlite/community

Of the items currently missing, I think the `Contributing` item is most important.  Documenting project conventions like code style rules (pep8, e.g.), testing tools etc would be helpful for new contributors. 

xref https://github.com/openjournals/joss-reviews/issues/3294

**Comment by FabianHofmann** [comment]
@kanderso-nrel we added a CONTRIBUTING.md which directs to the respective part in the documentation. A code of conduct did not seem necessary to us, so far. Please reopen if you still miss something
