### ISSUE TITLE
Could be possible to allow again more recent versions of `dask>=0.18.1`

### ISSUE THREAD

**Issue by fneum** [PyPSA/atlite#191]
https://github.com/PyPSA/atlite/blob/e1127d9946fdff4e5c2f63a2cb674147817d3ca4/setup.py#L35

https://github.com/dask/dask/issues/7583

https://docs.dask.org/en/stable/changelog.html#id4

https://github.com/dask/dask/pull/8040

**Comment by fneum** [comment]
`"dask>=0.18.0,!=2021.04.*,!=2021.05.*,!=2021.06.*,!=2021.07.*,!=2021.08.0",`

It's a bit long, but I didn't know how else to make OR statements in `setup.py`

**Comment by FabianHofmann** [comment]
good that you reminded me - yes, is possible :)
