### ISSUE TITLE
Add adaptor for loading windturbine powercurves from OpenEnergyDatabase

### ISSUE THREAD

**Issue by coroa** [PyPSA/atlite#21]
RLI built a list of 139 recent wind turbines collected from 11 different sources. They re-published them as a [table on their oedb](https://openenergy-platform.org/dataedit/view/supply/turbine_library) under an ODbL.

We should provide a small adaptor and instructions for querying this table and using it in atlite.

[saio](https://github.com/coroa/saio) is a great help for that.

**Comment by euronion** [comment]
Closing: #24 realises this feature.

The feature will be available in the new version which is currently in the last stages of development (see #20 ).
