### ISSUE TITLE
Use power low instead of log law for extrapolating wind speed

### ISSUE THREAD

**Issue by lukas-rokka** [PyPSA/atlite#231]
Use power low instead of log law for extrapolating wind speed to hub height.

## Description
The `extrapolate_wind_speed` function uses the power law and the grid averages forecast surface roughness (fsr):
 `wnd_spd = ds[from_name] * (   np.log(to_height / ds["roughness"]) / np.log(from_height / ds["roughness"])  )`
Using the ERA5 fsr with the log law results in too large correction, especially in the Nordics where the fsr is often high.  
At height above the blending height it is better to use the power law. That looks like follow:
`wnd_spd = ds["wnd100m"] * (to_height / 100)**a`. 
The wind sheer exponent `a` can be derived from the wind speed at 10m and 100m: 
`a = np.log(ds["wnd10m"] / ds["wnd100m"]) /  np.log(10 / 100)`. 
Tested it and it give same results as doing actual vertical interpolations with MetPy using the wind components from the pressure level data (how the ERA5 wind at 100 meters is orginally calculated as well).  

For turbines hub heights lower than the blending height it could be useful to use the log law to account for site specific roughness length. Below the equations from the IFS CY41R2 docs used to derive the 10m wind speed in ERA5 (always calculated assuming fsr of 0.03 to better represent conditions at weather stations)

<img width="490" alt="image" src="https://user-images.githubusercontent.com/20321019/162605133-35fc6188-aaf0-4744-88d0-75bacb96c232.png">
The IFS docs mention two blending heights, 40 and 75 meters (I guess it actually might be dynamic and site specific). But a procedure I use my self is to first use the above-mentioned power law to calculate a wind speed at a blending height of 70 meters, then the log law using a site specific fsr (for now, just some blunt estimates based on the ERA5 grid average fsr)

**Comment by euronion** [comment]
Thanks! Feature it is then. We could also have a parameter `interpolation_method` which takes `['automatic', 'log', 'power']` as arguments and if `automatic` is selected, then the appropriate logic based on the `hub_height` is selected.

We'd be happy to receive a PR for this :)
Else we'll probably have a look at it in May. Next weeks will be too busy with other things.

**Comment by lukas-rokka** [comment]
Task 2.3 in the new PECDv4 suggest using the power law as well https://climate.copernicus.eu/sites/default/files/2022-02/C3S2_412_Volume_II_final.pdf. It also says that there might be alpha coefficient (aka wind shear exponents) made available in CDS. So might be better to wait for what is being delivered from that project. 

I’m not that familiar with either PR or the structure of atlite so not sure I’m right person for the task. But basically, the steps would be to
1.	download also 10 m wind speeds
2.	calculate time varying alpha coefficient from wind 10m and 100m.  `ds["a"] = np.log(ds["wnd10m"] / ds["wnd100m"]) / np.log(10 / 100)`. (wind speed at 10 m can be discarded after this step).
3.	An `extrapolate_wind_speed_power_law function`, something like `wnd_hub = ds["wnd100m"] * (to_height / 100)**ds["a"]`
4.	Maybe a wrapper function for doing automatic, log law or power law extrapolation. 

Additionally or alternatively use alpha coefficient provide by PECDv4.

**Comment by wang99-123** [comment]
Hello, do you have knowledge about the calculation of wind shear coefficient PD model and can provide a detailed code?
