### ISSUE TITLE
Could you help upgrade the vulnerble dependency in atlite ? 

### ISSUE THREAD

**Issue by JoeGardner000** [PyPSA/atlite#232]
Hi, @coroa , @FabianHofmann , I'd like to report a vulnerability issue in **atlite_0.2.7**.
### Issue Description
I noticed that **atlite_0.2.7** directly depends on **rasterio_1.2.10**.
However, **rasterio_1.2.10** sufferes from the vulnerabilites which the C libraries exposed as following dependency graph shows. 
### Dependency Graph between Python and Shared Libraries
![image](https://user-images.githubusercontent.com/103017573/162616043-4f31d52c-546c-45a6-a750-41d419a60640.png)
### Suggested Vulnerability Patch Versions
**rasterio** has upgraded these vulnerable C libraries to patch versions refer to [issue url](https://github.com/rasterio/rasterio-wheels/issues/80#issue-1194815122).

Python build tools cannot report vulnerable C libraries, which may induce potential security issues to many downstream Python projects.
As a popular python package (**atlite** has **3,849** downloads per month), could you please upgrade this vulnerable dependency?

Thanks for your help~
Best regards,
Joe Gardner

**Comment by euronion** [comment]
Thanks @JoeGardner000 for bringing up this issue.
Do you have some best practice recommendations on how to tackle this (and similar issues) with research software?

My 2 cents: I don't think we should do anything to adress this issue for now:
* The best option would be to pin `rasterio` to the current `master` branch version (as a new `rasterio` has yet to be released), but I don't consider that a good approach.
* This is software for research with all its caveats.
* We're researchers, not sofware engineers/security professionals. I don't consider me qualified to do any assessment or offer a trust-worthy fix. And I certainly don't want to make this impression on users, that we do security assessments and monitoring.

If someone is concerned with security vulnerabilities, `atlite` can always be build and installed from the GitHub repo with the most-up-to-date dependencies.

What do you think @FabianHofmann ?

**Comment by FabianHofmann** [comment]
I agree, my preference would be to wait for a new `rasterio` release and add a minimum requirement.
