### ISSUE TITLE
[v0.2] Deprecation warnings are ignored by default

### ISSUE THREAD

**Issue by coroa** [PyPSA/atlite#27]
Uh annoying, they worked wonders in Python 2.7. The default has been changed to ignore them in `3.2` unless you add `-Wd` to your python interpreter or change the filter as you've shown. Hmm .. if I understand the manual correctly it's not intended for libraries to set `captureWarnings` or change the filter. I suppose we should warn in the manual about that and change the examples accordingly.

Do you think `logging.captureWarnings(True)` or `warnings.simplefilter('always', DeprecationWarning)` should be used? I'm tending towards the former.

_Originally posted by @coroa in https://github.com/FRESNA/atlite/pull/23/review_comment/create_

**Comment by euronion** [comment]
There seems to be quite a long story behind it, see e.g. https://lwn.net/Articles/740804/ .

I am in favour of activating them by default either with the `'always'` or `'module'` option.
Users of `atlite` are usually deep in their scripts and we are not talking about encapsulated script behaviour, but relevant API changes.

**Comment by coroa** [comment]
As described in https://github.com/FRESNA/atlite/pull/29#issuecomment-516024659, we should advocate the use of `warnings.simplefilter('default', DeprecationWarning)` to avoid overwhelming users.

**Comment by euronion** [comment]
Sounds good to me.

It is probably sufficient to just include it in the docs and examples, similar to what is already done with `logging` basic configuration.

**Comment by euronion** [comment]
I included sections on this in the documentaion as an example.

Do you think this suffices?
https://atlite.readthedocs.io/en/latest/examples/logfiles_and_messages.html

**Comment by coroa** [comment]
Yes, that looks good.

**Comment by euronion** [comment]
Great. Closing the issue.
