### ISSUE TITLE
Problems with installed dependencies from various sources

### ISSUE THREAD

**Issue by euronion** [PyPSA/atlite#3]
@hailiangliu89 and me are currently running into quite a few problems with installed dependencies.
Until now I think we were able to solve all the problems by using a different source for installation (or switching OS).

I don't think the causes can be solved from within `atlite`.
Is there a good way to cope with these problems?
The two obvious possibilities for me:

1. conda environment file
2. a FAQ section in the [README.rst](https://github.com/FRESNA/atlite/blob/master/README.rst)

Approach 1. would be more convinient, but I have the feeling that most problems are caused by the different, individual configurations.
This leaves approach 2., which would also be more versatile (and wouldn't require regular updates).

Any ideas?

Example:
For me installing `pyshp` from `conda-forge` causes problems, installing via `pip` works fine.
The same problem with `geopandas`.

Cheers.

**Comment by coroa** [comment]
When you use GIS stuff in conda, it works most of the time as long as you make sure ALL of it is from one channel. I usually explicitly request everything from conda-forge. See [environment.yaml](https://github.com/PyPSA/pypsa-eur/blob/master/environment.yaml) from pypsa-eur.

I'll leave this issue open as a reminder to create a conda-forge recipe for atlite!

**Comment by coroa** [comment]
There has been a conda-forge recipe for atlite now for a couple of months.
