### ISSUE TITLE
Read from url for `excluder.add_raster` and `excluder.add_geometry`

### ISSUE THREAD

**Issue by fneum** [PyPSA/atlite#307]
Would be nice to be able to do

```py
excluder.add_raster("https://mywebsite.org/file.nc")
```

**Comment by euronion** [comment]
Could follow same approach as in PyPSA for retrieving files in `_retrieve_from_url` https://github.com/PyPSA/PyPSA/blob/master/pypsa/io.py

**Comment by fneum** [comment]
Works with rasterio >= 1.3.2 automatically.
