### ISSUE TITLE
The problem of calculating average weather using normalized layout

### ISSUE THREAD

**Issue by wkxurn** [PyPSA/atlite#370]
Why is there a difference between using normalized layout and directly calculating the weather mean of some areas in the cutout when calculating the average weather?
I plan to calculate the average temperature of a certain area at each time, so I learned the method of using normalized layout calculation in the example Building stock weather aggregation.
`layout = layout / layout.sum()`
`cutout.temperature(layout=layout.fillna(0.0)).squeeze().to_series()`
The average temperature obtained is as follows：
![image](https://github.com/user-attachments/assets/20973353-9968-4091-8053-2e16643567c1)

However, I think this method differs greatly from normal weather values, even though the trend is similar. This result differs significantly from the result obtained when using cutout to directly calculate the average weather.
`cutout.data.temperature.sel(x=slice(19,21), y=slice(39,41)).mean(dim=["x", "y"])`
The average temperature obtained is as follows：
![image](https://github.com/user-attachments/assets/d87189a9-ab05-4f28-adab-9bac89ebd41d)

I am not sure if using normalized layout to calculate average weather is reasonable. Perhaps my understanding of using layout is incorrect. Please explain why layout is used as a parameter for `cutout.temperature.` Thank you very much!

**Comment by FabianHofmann** [comment]
@wkxurn could you point out which part varies so much? at first sight I cannot find significant changes. you can also subtract them (convert the first to K first of course) and then we have a look at the diff.

**Comment by wkxurn** [comment]
> 您能指出哪个部分差异如此之大吗？乍一看，我找不到明显的变化。您也可以减去它们（当然，首先将第一个转换为 K），然后我们看一下差异。



> @wkxurn could you point out which part varies so much? at first sight I cannot find significant changes. you can also subtract them (convert the first to K first of course) and then we have a look at the diff.

The difference in values on the vertical axis, with a maximum difference of ten times, but the two numbers are not in a tenfold relationship.

**Comment by wkxurn** [comment]
> @wkxurn could you point out which part varies so much? at first sight I cannot find significant changes. you can also subtract them (convert the first to K first of course) and then we have a look at the diff.

The difference in values on the vertical axis, with a maximum difference of ten times, but the two numbers are not in a tenfold relationship.

**Comment by FabianHofmann** [comment]
The one is in degree Celsius and the other in Kelvin, is that what you mean?

**Comment by wkxurn** [comment]
> The one is in degree Celsius and the other in Kelvin, is that what you mean?

You're right!! Thank you!! I didn't pay attention to the differences in units.
Also, I just discovered that cutout.py contains corresponding functions for me to calculate the average temperature and irradiation, but why isn't there a calculation for wind speed?

**Comment by FabianHofmann** [comment]
You are welcome :) there is none, as it was not necessary up to now, but could be implemented at any time
