### ISSUE TITLE
`atlite` is incompatible with `cdsapi` v0.7.3

### ISSUE THREAD

**Issue by irm-codebase** [PyPSA/atlite#379]
### Version Checks (indicate both or one)

- [X] I have confirmed this bug exists on the lastest [release](https://github.com/pypsa/atlite/releases) of Atlite.

- [ ] I have confirmed this bug exists on the current [`master`](https://github.com/pypsa/atlite/tree/master) branch of Atlite.

### Issue Description

`atlite` cannot download cutout data if the newest `cdsapi` version is present.
Pinning `cdsapi = 0.7.2` solves the problem, temporarily.

I'm not really sure if the issue is on the `cdsapi` side, or `atlite`'s though.

### Reproducible Example

```python
import atlite

# values are random, any cutout will fail
cutout = atlite.Cutout(
    module=['era5'],
    x=slice(3, 6),
    y=slice(3, 6),
    time="2019-05-02",
    features=['runoff'],
)
```

### Expected Behavior

Cutouts work.

### Installed Versions

<details>

v0.2.14

</details>

**Comment by fneum** [comment]
Has been dealt with here: https://github.com/PyPSA/atlite/pull/364/files

Are you sure you’re running on the latest atlite version?

**Comment by fneum** [comment]
Thanks for the hint @irm-codebase, though I don’t yet understand what changed in the cdsapi. It seems to be another dependency of cdsapi that breaks things.

**Comment by eliasinul** [comment]
> Has been dealt with here: https://github.com/PyPSA/atlite/pull/364/files
> 
> Are you sure you’re running on the latest atlite version?

Seems resolved. thanks for quick response !

**Comment by irm-codebase** [comment]
@irm-codebase glad to help!
The CDS move is just causing headaches left and right.
