### ISSUE TITLE
Implement configuration as object instead of module.

### ISSUE THREAD

**Issue by euronion** [PyPSA/atlite#45]
We do have (with the new version #20 ) a new configuration system in the pipeline.

It does however have a few downsides which became apparent during further developments, see e.g. the discussion here, where an observer can not trigger on changes of the module variables.

>> I don't think `__setattr__` is called on module level (but feel free to try, i am unsure).
>> We could package everything up into an object! :)
>
> Thought for the future:
> I worked on it in https://github.com/euronion/atlite/blob/f1e039abf9c5295ac549d0c39152beff7697c418/atlite/config.py
> and had a few things I could not figure out and dropped it.
> (like not calling the config as `atlite.config.config` and making sure the object is shared > among all modules when a new config-object is used to overwrite the existing one - in short:
> The current solution is more robust).

_Originally posted by @euronion in https://github.com/PyPSA/atlite/pull/43#issuecomment-520755345_

It would be nice to implement the config as a true object.

**Comment by coroa** [comment]
A serializable object would probably also help in distributed settings. In the current scheme, when using `from dask.distributed import Client; Client()`, the workers only see the default configuration, since they live in separate python processes.

**Comment by euronion** [comment]
We're not using a config object or configuration file anymore but instead opted for function arguments.
