### ISSUE TITLE
hour_shift caused non-unique index

### ISSUE THREAD

**Issue by hailiangliu89** [PyPSA/atlite#6]
>     WARNING: Because the original data is provided every month, at the
>     month boundaries there is untidiness if you use a time shift. The
>     resulting xarray will have duplicates in the index for the parts
>     of the day in each month at the boundary. You will have to
>     re-average these based on the number of hours in each month for
>     the duplicated day.

Hi Jonas, do you have an example of how to deal with the duplicated days? If not, I can try and add a function for it.

**Comment by coroa** [comment]
@nworbmot heat demand always fell into Tom's domain, so no i don't have an example at hand.

I'd appreciate new ideas on helping the user deal with the monthly boundaries.

**Comment by FabianHofmann** [comment]
upcoming in #20 see #79
