### ISSUE TITLE
[v0.2] Large memory overhead in cutout.pv

### ISSUE THREAD

**Issue by coroa** [PyPSA/atlite#61]
Different topic:
I failed to run `cutout.pv(...)` for the last days and found the problem to be insufficient memory (the script ran slowly and crashed at one point in time without a tractable error).
I solved it with `windows="D"`, which requires less data to be loaded into memory at the same time.

@coroa : What do you think about making `windows="D"` default for the convert operations?

_Originally posted by @euronion in https://github.com/PyPSA/atlite/pull/20#issuecomment-617057624_

**Comment by coroa** [comment]
For `heat_demand` windows="D" will be problematic since you want daylight adjusted windows.

Also atlite v0.0.1 works fine with monthly windows, so we should fix the bug where we introduced it. It's more likely to be a problem of not letting go of caches early enough.

Can you make your setup reproducible, ie. what cutout are you using?

**Comment by euronion** [comment]
> For `heat_demand` windows="D" will be problematic since you want daylight adjusted windows.

Can you elaborate why?

> Also atlite v0.0.1 works fine with monthly windows, so we should fix the bug where we introduced it. It's more likely to be a problem of not letting go of caches early enough.
> 
> Can you make your setup reproducible, ie. what cutout are you using?

`europe-2013-sarah` as used in PyPSA-EUR, i.e.
```
> cutout
<Cutout europe-2013-sarah x=-12.00-41.80 y=33.00-64.80 time=2013-01-01-2013-12-31 prepared_features=['temperature', 'influx'] is_view=False>
```

**Comment by FabianHofmann** [comment]
tackled in #20

**Comment by coroa** [comment]
> Can you elaborate why?

Sorry for the long delay, the answer is in my comment to #79 .
