### ISSUE TITLE
era5: wrong coordinate system for 'odd' bounds in cutout

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/atlite#64]
When passing odd bounds as cutout parameters, the retrieved data is misaligned to the built coordinate system.

For example 
```python 
cutout = atlite.Cutout(path="uk-2011-01",
                       module="era5",
                       bounds=(-14.1, 50.34, 1.512, 61.123),
                       time="2011-01-01")
cutout.prepare()
```
will try to retrieve data for a grid beginning with -14.1 followed by steps of 0.25. However the coordinate system set up (automaticaly before `cutout.prepare()`) begins with -14.0 followed by steps of 0.25. 

`atilite` merges the original grid with the retrieved data without an error, which ends up in a lot of nan's

**Comment by euronion** [comment]
Closed in #65
