### ISSUE TITLE
Add Test Script(s)

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/atlite#66]
Since we're still having some trouble to properly intergrate v0.2 (#20), it would be helpful to add a test script which canvasses major relations. 

Atm I'm trying to figure out how this would look like. Some things I have in mind:

* Check coordinate alignment. As seen in #62 coordinates are a sensitive thing, if they are wrong, you get nice twisted pictures. This is probably a small check that coordinates of all retrieved data and converted data are in increasing order.
* Check shape of the cutout against the target shape, given by bounds and resolution
* Check against occurrence of nan values. If you have nan values in your retrieved data (not converted) then something is wrong.
 

This list should continue. I'm starting to write down some test files. Feel free to add to the list

**Comment by euronion** [comment]
I think running conversion checks with the different types of conversion functions should also be included, e.g. on a cutout (or fake cutout, i.e. providing a `xarray.DataSet` with the necessary variables hard coded and:

* CFs with a predetermined PV panel
* CFs with predetermined wind turbine
* `hydro` ror generation time-series

and compare it against a reference.

These are the essential functions for `atlite` which I think make sense to have atleast included.

**Comment by FabianHofmann** [comment]
Alright, perhaps a rough division into 

* test_cutout_creation.py
* test_alignment.py
* test_conversion.py

Probably the sparse array operations should also flow into a separate test.
* test_sparse_operations.py

But let's see where we get...
