### ISSUE TITLE
Necessity of Sarah SIS and SID Interpolation

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/atlite#75]
The original sarah datasets, SID and SIS, have both a band of nans along the earth where dawn and nightfall takes place. On one side you find mostly values > 0, on the other only values of 0. 

![sarah_sid_10](https://user-images.githubusercontent.com/19226431/82954750-a7b46f00-9fad-11ea-820c-44034dc18a57.png)
![sarah_sis_20](https://user-images.githubusercontent.com/19226431/82954756-ac792300-9fad-11ea-820c-110b134ef580.png)

Atm we are extensively interpolating those areas with a 1d interpolation, which for large cutouts takes a lot of time. The question raises, is the interpolation necessary.

**Comment by euronion** [comment]
Could you determine whether the interpolation is necessary?

**Comment by FabianHofmann** [comment]
Yes, it's not the case, the interplolation function is fast.

**Comment by euronion** [comment]
Are you sure about this?
I dug out the profiling I did last week (small UK cutout):

![grafik](https://user-images.githubusercontent.com/42553970/83126011-8d2ae480-a0d8-11ea-9003-293556d463d0.png)

Based on that
* I would agree that a single interpolation is fast (time percall < 1s)
* The number of calls is extremly high due to the way the data is decomposited such that we get `ncalls = 6221` in the example and the majority of the cumulated time somewhere in the interpolation step (`~ 4800 s`).

**Comment by coroa** [comment]
Interpolation is necessary for older years in sarah, i think there was an analysis in [Pfenninger 2016](https://www.sciencedirect.com/science/article/pii/S0360544216311744)

**Comment by euronion** [comment]
Thanks for the clarification!

They mention as a reason for interpolating (pg. 1253):

> For the analysis performed here, missing periods of 6 h or shorter are interpolated from neighboring values. Longer periods are filled by taking data for the same dates from the preceding year (or the subsequent year in the first year ofdata), and adjusting by the between-year difference in mean of the 7 days before and after the missing period. The amount of missing data and the difference between raw and filled SARAH data is shown later in Fig. 11.

![grafik](https://user-images.githubusercontent.com/42553970/83636459-4e000600-a5a6-11ea-9690-8af186830576.png)

The relevant area is the gray one.

What do you think @FabianHofmann ?

**Comment by coroa** [comment]
And some more fuzzy tidbit from me, either from 2000 or from 2010, there wasn't any periods longer than 6h, that's why i implemented only the first half of what stefan did.

**Comment by FabianHofmann** [comment]
closing this, the interpolation can now be turned off in #20
